import { createRouter, createWebHashHistory } from 'vue-router'

const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    { path: '/',            component: () => import('@/pages/Dashboard.vue') },
    { path: '/graph',       component: () => import('@/pages/GraphExplorer.vue') },
    { path: '/matrix',      component: () => import('@/pages/MatrixExplorer.vue') },
    { path: '/vector',      component: () => import('@/pages/VectorExplorer.vue') },
    { path: '/ai',          component: () => import('@/pages/AIWorkbench.vue') },
    { path: '/scenarios',   component: () => import('@/pages/ScenarioExplorer.vue') },
    { path: '/collections', component: () => import('@/pages/DataCollections.vue') },
    { path: '/compare',     component: () => import('@/pages/GraphCompare.vue') },
    { path: '/workbench',   component: () => import('@/pages/GraphWorkbench.vue') },
    { path: '/scaffold',    component: () => import('@/pages/industries/scaffold/ScaffoldPlanner.vue') },
    { path: '/mfg',         component: () => import('@/pages/MfgBomPlanner.vue') },
    { path: '/pipeline',    component: () => import('@/pages/PipelinePlanner.vue') },
    { path: '/network-security', component: () => import('@/pages/industries/network-security/NetworkSecurityExplorer.vue') },
    { path: '/ai-training',           component: () => import('@/pages/industries/ai-training/AITrainingHub.vue') },
    { path: '/ai-training/datasets',  component: () => import('@/pages/industries/ai-training/DatasetManager.vue') },
    { path: '/ai-training/datasets/new', component: () => import('@/pages/industries/ai-training/DatasetBuilder.vue') },
    { path: '/ai-training/train',     component: () => import('@/pages/industries/ai-training/TrainingConfig.vue') },
    { path: '/ai-training/monitor',   component: () => import('@/pages/industries/ai-training/TrainingMonitor.vue') },
    { path: '/ai-training/models',    component: () => import('@/pages/industries/ai-training/ModelRegistry.vue') },
    { path: '/ai-training/playground', component: () => import('@/pages/industries/ai-training/Playground.vue') },
    { path: '/drug-discovery',  component: () => import('@/pages/industries/drug-discovery/DrugDiscoveryExplorer.vue') },
    { path: '/genomics',        component: () => import('@/pages/industries/genomics/GenomicsExplorer.vue') },
    { path: '/semiconductor',   component: () => import('@/pages/industries/semiconductor/SemiconductorExplorer.vue') },
    { path: '/threat-intel',    component: () => import('@/pages/industries/threat-intel/ThreatIntelligenceExplorer.vue') },
    { path: '/aml',             component: () => import('@/pages/industries/aml/AMLExplorer.vue') },
    { path: '/legal',           component: () => import('@/pages/industries/legal/LegalExplorer.vue') },
    { path: '/materials',       component: () => import('@/pages/industries/materials/MaterialsExplorer.vue') },
    { path: '/plugins',     component: () => import('@/pages/PluginManager.vue') },
    { path: '/self',        component: () => import('@/pages/SelfGraph.vue') },
    { path: '/erp',         component: () => import('@/pages/industries/erp/ERPHub.vue') },
    { path: '/erp/graph',   component: () => import('@/pages/industries/erp/ERPGraph.vue') },
    { path: '/erp/data',    component: () => import('@/pages/industries/erp/ERPData.vue') },
    { path: '/projects',               component: () => import('@/pages/projects/ProjectHub.vue') },
    { path: '/projects/:id',           component: () => import('@/pages/projects/ProjectDetail.vue') },
    { path: '/projects/:id/smart',     component: () => import('@/pages/projects/ProjectSmartView.vue') },
    { path: '/projects/:id/gantt',     component: () => import('@/pages/projects/ProjectGantt.vue') },
    { path: '/projects/:id/analytics', component: () => import('@/pages/projects/ProjectAnalytics.vue') },
    { path: '/supply-chain',     component: () => import('@/pages/supply-chain/SupplyChainHub.vue') },
    { path: '/mrp',              component: () => import('@/pages/mrp/MRPHub.vue') },
    { path: '/mrp/planner',      component: () => import('@/pages/mrp/MRPPlanner.vue') },
    { path: '/mrp/cost-centers', component: () => import('@/pages/mrp/MRPCostCenters.vue') },
    { path: '/mrp/orders',       component: () => import('@/pages/mrp/MRPOrders.vue') },
  ]
})

export default router
